//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hydocs.Areas.AdWorks.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorks : DbContext
    {
        /// <summary>
        /// A model DB context class, contains virtual Customers and Products classes
        /// </summary>
        public AdventureWorks()
            : base("name=AdventureWorks")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
           
        }
    
        /// <summary>
        /// Customers - a demo model  virtual class
        /// </summary>
        public virtual DbSet<Customer> Customers { get; set; }
        /// <summary>
        /// Products - a demo model  virtual class
        /// </summary>
        public virtual DbSet<Product> Products { get; set; }
        //public virtual DbSet<ProductDTO> ProductsDTO { get; set; }
    }
}
