
<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <div class="row">
        <h1>An MVC 6 demo</h1>
           <h3><span class="h4">I am a classic Web Form. I want to show you, I can co-exist with MVC 5 areas and Web API inside the same web application / Visual Studio project. </span> </h3>
        <p style="height: 7px">&nbsp;</p>
              <table style="width: 75%; position:center" align="center" >
                  <caption>
                      <strong class="navbar">Web Pages + MVC 5 + Web API = MVC 6<br />
                      </strong></caption>
        <tr>
            <td style="background-color: #CCCCCC; height: 30px;" class="text-center"><b class="nav">Web Pages</b></td>
            <td style="background-color: #999999; class="text-center" class="text-center"><b>MVC 5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </b></td>
            <td style=" background-color: #BF91A0; class="text-center" class="text-center"><b>Web API</b></td>
        </tr>
        <tr>
            <td class="razorRow" colspan="2">Razor</td>
          <td style="background-color: #BF91A0"></td>
        </tr>
        <tr>
          <td  class="razorRow" colspan="2">HTML Helpers</td>
            <td style="background-color: #BF91A0"></td>
        </tr>
                <tr>
            <td style="background-color: #CCCCCC">&nbsp;</td>
             <td  class="razorRow" colspan="2">Controllers</td>
        </tr>
                     <tr>
            <td style="background-color: #CCCCCC">&nbsp;</td>
            <td colspan="2" class="razorRow" >Actions</td>
             
        </tr>
                     <tr>
            <td style="background-color: #CCCCCC">&nbsp;</td>
             <td class="razorRow" colspan="2" >Filters</tr>
       
                     <tr>
            <td style="background-color: #CCCCCC">&nbsp;</td>
               <td class="razorRow" colspan="2" >Model Binding</td>
        </tr>
       
                     <tr>
            <td style="background-color: #CCCCCC">&nbsp;</td>
               <td class="razorRow" colspan="2" >Dependency Resolver</td>
        </tr>
       
                     <tr>
            <td style="background-color: #CCCCCC">&nbsp;</td>
                     <td style="background-color: #999999"></td>
                       <td style="background-color: #BF91A0"></td>
        </tr>
       
    </table>
  
      </div>
   
    <div class="row">
          <div class="col-md-3">
                  <h2>ASP.NET Web Form</h2>
                      <p>
       A demo with the sample Adventure Works database, a List View and&nbsp; an Object Data source (MVC 5 model)<br /> </p>
            <p>
                    <br />
                <a class="btn btn-default" href="wfdemo">Try List View &raquo;</a>
            </p>    
        </div>
        <div class="col-md-3">
                  <h2>MVC Area </h2>
                  <p>Another demo with Adventure Works database plus a very deft React search.  </p>
                   <br />    <br />
             
            <p>
                <a class="btn btn-default" href="adworks/customersmv">Try MVC View and React &raquo;</a>
            </p>    
        </div>
    
        <div class="col-md-3">
            <h2>MS Web API docs</h2>
            <p>
         Autogenerated&nbsp; demo API documentation  </p>
         <br />  <br />    <br />
            <p>
                <a class="btn btn-default"  href="help">View Web API docs &raquo;</a>
            </p>
          
        </div>
            <div class="col-md-3">
            <h2>Swagger docs</h2>
            <p>
         Swagger can run within VS side by side with Microsoft WebAPI Help Page.</p>
             <br />    <br />
                          <p>
                <a class="btn btn-default"  href="swaggerdemo">View Swagger docs &raquo;</a>
            </p>
        </div>
        <div style="float:right">
    <img style="-webkit-user-select: none;background-position: 0px 0px, 10px 10px;background-size: 20px 20px;background-color: white;background-image:linear-gradient(45deg, #eee 25%, transparent 25%, transparent 75%, #eee 75%, #eee 100%),linear-gradient(45deg, #eee 25%, transparent 25%, transparent 75%, #eee 75%, #eee 100%);" src="https://i.stack.imgur.com/xtpSX.gif">
   </div>
    </div>
  
</asp:Content>
